# Generated by Django 2.0.2 on 2018-04-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='operating_system',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='dimensions',
            field=models.CharField(help_text='In cm', max_length=200),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.FloatField(help_text='In kg'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('i', 'Intel'), ('a', 'AMD')], help_text='Manufacturer type', max_length=1),
        ),
    ]
