# Generated by Django 2.0.2 on 2018-04-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0002_auto_20180415_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='manufacturer',
            field=models.CharField(choices=[('i', 'Intel'), ('a', 'AMD')], help_text='Manufacturer type', max_length=1),
        ),
    ]
