# Generated by Django 2.0.2 on 2018-04-15 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0003_auto_20180415_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(choices=[('a', 'AMD'), ('i', 'Intel'), ('n', 'Nvidia')], default='n', help_text='Manufacturer type', max_length=1)),
                ('type', models.CharField(choices=[('d', 'Discrete'), ('i', 'Integrated')], default='d', help_text='Discrete or integrated', max_length=1)),
                ('architecture', models.CharField(max_length=100)),
                ('core_base_speed', models.IntegerField(help_text='In MHz')),
                ('core_turbo_speed', models.IntegerField(help_text='In MHz')),
                ('memory', models.IntegerField(help_text='In MB')),
                ('memory_speed', models.IntegerField(help_text='In MHz')),
                ('memory_bus_width', models.IntegerField(help_text='In Bits')),
                ('pipelines', models.IntegerField()),
                ('manufacturing_technology', models.IntegerField(help_text='In nm')),
            ],
            options={
                'ordering': ['model_name'],
            },
        ),
        migrations.AddField(
            model_name='laptop',
            name='brand_name',
            field=models.CharField(choices=[('ac', 'Acer'), ('ap', 'Apple'), ('as', 'Asus'), ('d', 'Dell'), ('g', 'Gigabyte'), ('hp', 'HP'), ('hu', 'Huawei'), ('l', 'Lenovo'), ('mi', 'Microsoft'), ('ms', 'MSI'), ('r', 'Razer')], default='ac', help_text='Brand name', max_length=1),
        ),
        migrations.AddField(
            model_name='laptop',
            name='operating_system',
            field=models.CharField(choices=[('m', 'MacOS'), ('w', 'Windows 10')], default='w', help_text='Opearating system', max_length=1),
        ),
        migrations.AlterField(
            model_name='processor',
            name='manufacturer',
            field=models.CharField(choices=[('a', 'AMD'), ('i', 'Intel')], default='i', help_text='Manufacturer type', max_length=1),
        ),
        migrations.AddField(
            model_name='laptop',
            name='graphics_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webpage.GraphicsCard'),
        ),
    ]
