# Generated by Django 2.0.2 on 2018-04-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0004_auto_20180415_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='brand_name',
            field=models.CharField(choices=[('Acer', 'Acer'), ('ap', 'Apple'), ('as', 'Asus'), ('d', 'Dell'), ('g', 'Gigabyte'), ('hp', 'HP'), ('hu', 'Huawei'), ('l', 'Lenovo'), ('mi', 'Microsoft'), ('ms', 'MSI'), ('r', 'Razer')], default='ac', help_text='Brand name', max_length=8),
        ),
    ]
