# Generated by Django 2.0.2 on 2018-04-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0005_auto_20180415_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='brand_name',
            field=models.CharField(choices=[('Acer', 'Acer'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Dell', 'Dell'), ('Gigabyte', 'Gigabyte'), ('HP', 'HP'), ('Huawei', 'Huawei'), ('Lenovo', 'Lenovo'), ('Microsoft', 'Microsoft'), ('MSI', 'MSI'), ('Razer', 'Razer')], default='ac', help_text='Brand name', max_length=8),
        ),
    ]
