# Generated by Django 2.0.2 on 2018-04-15 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0006_auto_20180415_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4')], default='DDR4', help_text='DDR3 or DDR4', max_length=8)),
                ('frequency', models.IntegerField(help_text='In MHz')),
                ('size', models.IntegerField(help_text='In MB')),
                ('max_size', models.IntegerField(help_text='In MB')),
            ],
            options={
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='StorageDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(choices=[('Adata', 'Adata'), ('Intel', 'Intel'), ('Kingston', 'Kingston'), ('Samsung', 'Samsung'), ('SanDisk', 'SanDisk'), ('Seagate', 'Seagate'), ('Transcend', 'Transcend'), ('WD', 'WD')], default='Samsung', help_text='Manufacturer type', max_length=8)),
                ('type', models.CharField(choices=[('hdd', 'HDD'), ('ssd', 'SSD')], default='d', help_text='HDD or SSD', max_length=8)),
                ('read_speed', models.IntegerField(help_text='In MB/s')),
                ('write_speed', models.IntegerField(help_text='In MB/s')),
                ('size', models.IntegerField(help_text='In MB')),
            ],
            options={
                'ordering': ['model_name'],
            },
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='manufacturer',
            field=models.CharField(choices=[('AMD', 'AMD'), ('Intel', 'Intel'), ('Nvidia', 'Nvidia')], default='Intel', help_text='Manufacturer type', max_length=8),
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='type',
            field=models.CharField(choices=[('d', 'Discrete'), ('i', 'Integrated')], default='d', help_text='Discrete or integrated', max_length=8),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='brand_name',
            field=models.CharField(choices=[('Acer', 'Acer'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Dell', 'Dell'), ('Gigabyte', 'Gigabyte'), ('HP', 'HP'), ('Huawei', 'Huawei'), ('Lenovo', 'Lenovo'), ('Microsoft', 'Microsoft'), ('MSI', 'MSI'), ('Razer', 'Razer')], default='Acer', help_text='Brand name', max_length=8),
        ),
        migrations.AlterField(
            model_name='processor',
            name='manufacturer',
            field=models.CharField(choices=[('AMD', 'AMD'), ('Intel', 'Intel')], default='Intel', help_text='Manufacturer type', max_length=8),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webpage.RAM'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage_drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webpage.StorageDrive'),
        ),
    ]
