# Generated by Django 2.0.2 on 2018-04-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0008_auto_20180415_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IPS', 'IPS'), ('TN', 'TN')], default='IPS', help_text='IPS or TN type of display', max_length=8)),
                ('refresh_rate', models.IntegerField(help_text='In Hz')),
                ('size', models.CharField(help_text='In inches', max_length=20)),
                ('resolution', models.CharField(help_text='Horizontal on verical resolution', max_length=100)),
            ],
            options={
                'ordering': ['size'],
            },
        ),
        migrations.AddField(
            model_name='laptop',
            name='display',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webpage.Display'),
        ),
    ]
