# Generated by Django 2.0.2 on 2018-04-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0009_auto_20180415_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='laptop',
            name='depth',
            field=models.FloatField(default=3, help_text='In cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='height',
            field=models.FloatField(default=20, help_text='In cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='width',
            field=models.FloatField(default=15, help_text='In cm'),
            preserve_default=False,
        ),
    ]
