# Generated by Django 2.0.2 on 2018-04-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0010_auto_20180415_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagedrive',
            name='size',
            field=models.IntegerField(help_text='In GB'),
        ),
    ]
