# Generated by Django 2.0.2 on 2018-04-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0011_auto_20180416_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='graphics_card',
        ),
        migrations.AddField(
            model_name='laptop',
            name='graphics_card',
            field=models.ManyToManyField(to='Webpage.GraphicsCard'),
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='storage_drive',
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage_drive',
            field=models.ManyToManyField(to='Webpage.StorageDrive'),
        ),
    ]
