# Generated by Django 2.0.2 on 2018-06-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0015_auto_20180503_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphicscard',
            name='type',
            field=models.CharField(choices=[('Discrete', 'Discrete'), ('Integrated', 'Integrated')], default='d', help_text='Discrete or integrated', max_length=12),
        ),
    ]
