# Generated by Django 2.0.2 on 2018-06-03 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0017_auto_20180603_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular laptop across whole laptop database', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('f', 'Favourite'), ('d', 'default')], default='d', help_text='Laptop status', max_length=1)),
                ('laptop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Webpage.Laptop')),
            ],
        ),
    ]
