# Generated by Django 2.0.2 on 2018-06-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0017_auto_20180603_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='status',
            field=models.CharField(blank=True, choices=[('l', 'Like'), ('d', 'Dislike')], help_text='Status', max_length=8),
        ),
    ]
