# Generated by Django 2.0.2 on 2018-06-04 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webpage', '0018_laptopinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopinstance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laptopinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('l', 'Like'), ('d', 'Dislike')], help_text='Status', max_length=8),
        ),
    ]
