# Generated by Django 2.0.2 on 2018-06-04 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webpage', '0019_laptop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='user',
        ),
        migrations.AddField(
            model_name='laptop',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
