# Generated by Django 2.0.2 on 2018-06-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0019_auto_20180604_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptopinstance',
            options={'permissions': (('can_mark_liked', 'Set laptop as liked'),)},
        ),
    ]
