# Generated by Django 2.0.2 on 2018-06-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0020_auto_20180604_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptopinstance',
            options={'permissions': (('can_mark_liked', 'Set laptop as liked'), ('can_mark_disliked', 'Set laptop as disliked'))},
        ),
    ]
