# Generated by Django 2.0.2 on 2018-06-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0021_auto_20180604_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptopinstance',
            old_name='user',
            new_name='normal_user',
        ),
    ]
