# Generated by Django 2.0.2 on 2018-06-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0021_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'permissions': (('can_see_all_favorited', 'See all favorited laptops'),)},
        ),
    ]
