# Generated by Django 2.0.2 on 2018-06-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0022_auto_20180614_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'permissions': (('can_see_all_favorited', 'See all favorited laptops'), ('can_create_laptop', 'Create new laptop on the webpage'))},
        ),
    ]
