# Generated by Django 2.0.2 on 2018-06-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0022_auto_20180604_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptopinstance',
            options={'permissions': (('can_mark_liked', 'Set laptop as liked'), ('can_mark_disliked', 'Set laptop as disliked'), ('can_see_all_liked', 'See all liked laptops'))},
        ),
    ]
