# Generated by Django 2.0.2 on 2018-06-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0023_auto_20180604_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptopinstance',
            old_name='normal_user',
            new_name='person',
        ),
    ]
