# Generated by Django 2.0.2 on 2018-06-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0024_auto_20180604_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptopinstance',
            options={'permissions': (('can_mark_liked', 'Set laptop as liked'), ('can_mark_disliked', 'Set laptop as disliked'), ('can_see_all_liked', 'See all liked laptops'), ('can_see_all_disliked', 'See all disliked laptops'))},
        ),
    ]
