# Generated by Django 2.0.2 on 2018-06-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webpage', '0024_auto_20180616_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamlaptop',
            name='description',
            field=models.CharField(default='Sample decription', help_text='Small description for your computer', max_length=200),
            preserve_default=False,
        ),
    ]
