# Generated by Django 2.0.2 on 2018-06-17 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webpage', '0025_dreamlaptop_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dreamlaptop',
            name='creator',
        ),
        migrations.AddField(
            model_name='dreamlaptop',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
